export const ADD_TO_CART = "ADD_TO_CART";
export const LOAD_CART_FROM_STORAGE = "LOAD_CART_FROM_STORAGE";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const LOAD_SHIPPING_INFO_FROM_STORAGE =
  "LOAD_SHIPPING_INFO_FROM_STORAGE";

export const LOAD_ORDER_CONFIRMATION_FROM_STORAGE =
  "LOAD_ORDER_CONFIRMATION_FROM_STORAGE";
